
---

###############################################################################
# general configuration, not tied to any specific course
# point person: undergraduate committee
###############################################################################
- hosts: localhost
  remote_user: root
  tasks:

    - name: update system packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: VirtualBox guest additions
      apt: name={{item}} state=present
      with_items:
        - virtualbox-guest-dkms
        - virtualbox-guest-utils
        - virtualbox-guest-x11

    - name: convenient packages
      apt: name={{item}} state=present
      with_items:
        - chromium-browser
        - emacs
        - vim

###############################################################################
# CPSC 120-121-131 official environment
# point person: undergraduate committee
###############################################################################
- hosts: localhost
  remote_user: root
  tasks:

    - name: g++ 5 compiler
      apt: name={{item}} state=present
      with_items:
        - build-essential
        - g++-5

    - name: gdb debugger
      apt: name=gdb state=present

    - name: Atom editor
      apt: deb=https://atom.io/download/deb

    - name: Atom gdb support
      command: /usr/bin/apm install dbg-gdb dbg output-panel

    - name: git
      apt: name=git state=present

    - name: media computation
      apt: name={{item}} state=present
      with_items:
        - audacity
        - gimp
        - libsdl2-dev
        - nlohmann-json-dev

###############################################################################
# CPSC 484
# point person: Kevin Wortman
###############################################################################

- hosts: localhost
  remote_user: root
  tasks:

    - name: OpenGL and related libraries
      apt: name={{item}} state=present
      with_items:
        - freeglut3-dev
        - libglu1-mesa-dev
        - libglew-dev
        - libgl1-mesa-dev

###############################################################################
# CPSC 598, scholarly papers
# point person: Kevin Wortman
###############################################################################

- hosts: localhost
  remote_user: root
  tasks:

    - name: LaTeX
      apt: name=texlive-full state=present

...
